import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createSender,createOpener} from '../index.js';
import {createLifecycle} from '../lifecycle.js';
import {createPatternFinder} from '../patterns.js';
const require=createRequire(import.meta.url);
const {JSDOM}=require(process.env.GHOST_TEST_JSDOM || 'jsdom');
function clock(){let now=1000,next=0;const tasks=new Map();return {now:()=>now,setTimeout(fn,ms){const id=++next;tasks.set(id,{fn,at:now+ms});return id;},clearTimeout:id=>tasks.delete(id),get pending(){return tasks.size;},async advance(ms){const end=now+ms;for(let safety=0;safety<10000;safety++){await Promise.resolve();await Promise.resolve();await Promise.resolve();const due=[...tasks].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due){now=end;return;}now=due[1].at;tasks.delete(due[0]);due[1].fn();}throw Error('Clock runaway');}};}
function fixture(html=''){const dom=new JSDOM('<!doctype html><body>'+html,{url:'https://web.snapchat.com',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.getBoundingClientRect=function(){return this.isConnected && !this.hidden?{width:100,height:30,left:0,top:0,right:100,bottom:30}:{width:0,height:0,left:0,top:0,right:0,bottom:0};};w.document.elementFromPoint=()=>w.document.querySelector('div.vwM69.OXbMa')||w.document.body;w.HTMLElement.prototype.scrollIntoView=()=>{};return dom;}
test('import has no browser requirement',()=>{assert.equal(typeof createSender,'function');assert.equal(typeof createOpener,'function');});
test('lifecycle cancels timers and cannot restart after disposal',async()=>{const c=clock(),l=createLifecycle({clock:c});l.begin();const p=l.sleep(100);l.stop();await assert.rejects(p,{name:'AbortError'});assert.equal(c.pending,0);l.dispose();assert.throws(()=>l.begin(),/disposed/);});
for(const [name,factory,config] of [['sender',createSender,{recipients:['Approved fixture']}],['single opener',createOpener,{}],['multi opener',createOpener,{mode:'multi',recipients:['Approved fixture']}]]){
 test(name+' missing DOM: independent instances, cancellation and restart',async()=>{const dom=fixture(),c=clock(),errors=[];const a=factory({document:dom.window.document,clock:c,onError:e=>errors.push(e),...config});const b=factory({document:dom.window.document,clock:c,...config});const initial=b.getState();try{a.start();await c.advance(250);assert.equal(a.getState().running,true);assert.deepEqual(b.getState(),initial);await a.stop();assert.equal(a.getState().running,false);assert.equal(c.pending,0);a.start();await c.advance(100);await a.dispose();assert.equal(c.pending,0);assert.throws(()=>a.start(),/disposed/);assert.deepEqual(errors,[]);}finally{await a.dispose();await b.dispose();dom.window.close();}});
}
test('multi missing recipient and sender missing recipient reject without starting',()=>{const dom=fixture();try{assert.throws(()=>createSender({document:dom.window.document}).start(),/recipient/);assert.throws(()=>createOpener({document:dom.window.document,mode:'multi'}).start(),/recipients/);}finally{dom.window.close();}});
test('strict single failed transition does not count a click as an open',async()=>{const dom=fixture('<div class="vwM69 OXbMa">view</div>'),c=clock(),errors=[];let clicks=0;dom.window.document.querySelector('div').onclick=()=>clicks++;const a=createOpener({document:dom.window.document,clock:c,allowLegacyClickFallback:false,onError:e=>errors.push(e)});try{a.start();await c.advance(5000);await a.stop();assert(clicks>0);assert.equal(a.getState().snapsOpened,0);assert.deepEqual(errors,[]);assert.equal(c.pending,0);}finally{await a.dispose();dom.window.close();}});
test('legacy single timeout fallback counts at most once per clicked cycle',async()=>{const dom=fixture('<div class="vwM69 OXbMa">view</div>'),c=clock(),counts=[];const a=createOpener({document:dom.window.document,clock:c,onDiagnostic:e=>{if(e.event==='open_counted')counts.push(e);}});try{a.start();await c.advance(5000);await a.stop();assert(counts.length>0);assert.equal(new Set(counts.map(e=>e.cycleId)).size,counts.length);assert(counts.every(e=>!e.strictProof));assert.equal(a.getState().snapsOpened,counts.length);}finally{await a.dispose();dom.window.close();}});
test('shared canvas compatibility patch is reference-counted',async()=>{const dom=fixture(),c=clock(),original=dom.window.HTMLCanvasElement.prototype.toBlob;const a=createSender({document:dom.window.document,clock:c,recipients:['A']}),b=createSender({document:dom.window.document,clock:c,recipients:['B']});try{a.start();b.start();const patch=dom.window.HTMLCanvasElement.prototype.toBlob;assert.notEqual(patch,original);await a.stop();assert.equal(dom.window.HTMLCanvasElement.prototype.toBlob,patch);await b.stop();assert.equal(dom.window.HTMLCanvasElement.prototype.toBlob,original);}finally{await a.dispose();await b.dispose();dom.window.close();}});
test('pattern cache rejects detached elements and low-confidence unknown targets',async()=>{const dom=fixture('<button class="qJKfS">Camera</button>');try{const {finder}=createPatternFinder(dom.window.document);const old=dom.window.document.querySelector('button');const fingerprint=finder.fingerprinter.createElementFingerprint(old);const find=()=>finder.findElement(fingerprint,{fallbackSelectors:['button.qJKfS'],threshold:0.5});assert.equal((await find()).element,old);const replacement=old.cloneNode(true);old.replaceWith(replacement);assert.equal((await find()).element,replacement);replacement.remove();assert.equal((await find()).element,null);assert.equal((await finder.findElement({tagName:'BUTTON',textContent:'never matches',classList:['no-such-class']},{threshold:0.99})).element,null);}finally{dom.window.close();}});
for(const mode of ['single','multi'])test(mode+' delayed viewer and return count one verified cycle',async()=>{const markup=mode==='single'?'<div class="vwM69 OXbMa">view</div>':'<div class="deg2K"><div class="O4POs"><span class="FiLwP">Approved fixture</span><span class="giV53"><span class="nonIntl">View</span></span><button class="HEkDJ">View</button></div></div>';const dom=fixture(markup),d=dom.window.document,c=clock(),errors=[],diagnostics=[];const list=d.body.firstElementChild,button=mode==='single'?list:d.querySelector('.HEkDJ');button.onclick=()=>c.setTimeout(()=>{list.remove();const viewer=d.createElement('section');viewer.innerHTML='<button>Send To</button><button>Download</button><button aria-label="Back">Back</button>';viewer.querySelector('[aria-label]').onclick=()=>{viewer.remove();d.body.append(list);};d.body.append(viewer);},80);let a;a=createOpener({document:d,mode,recipients:['Approved fixture'],clock:c,allowLegacyClickFallback:false,onDiagnostic:e=>diagnostics.push(e),onError:e=>errors.push(e),onProgress:s=>{if(s.snapsOpened===1)a.stop();}});try{a.start();await c.advance(3000);await a.stop();assert.equal(a.getState().snapsOpened,1);assert.deepEqual(errors,[]);assert.equal(c.pending,0);}finally{await a.dispose();dom.window.close();}});
test('failed click and mid-transition disposal do not leave timers or counts',async()=>{const dom=fixture('<div class="vwM69 OXbMa">view</div>'),c=clock(),target=dom.window.document.querySelector('div');target.click=()=>{throw Error('synthetic click failure');};const a=createOpener({document:dom.window.document,clock:c,allowLegacyClickFallback:false});try{a.start();await c.advance(2000);await a.dispose();assert.equal(a.getState().snapsOpened,0);assert.equal(c.pending,0);assert.equal(a.getState().running,false);}finally{dom.window.close();}});
for(const acknowledged of [true,false])test('sender complete selection '+(acknowledged?'acknowledged once':'ack timeout does not count'),async()=>{const dom=fixture(),w=dom.window,d=w.document,c=clock(),errors=[],states=[];Object.defineProperty(w.HTMLElement.prototype,'offsetWidth',{get(){return this.isConnected?100:0;}});Object.defineProperty(w.HTMLElement.prototype,'offsetHeight',{get(){return this.isConnected?30:0;}});function show(stage){d.body.innerHTML=stage==='camera'?'<button class="qJKfS">Camera</button>':stage==='capture'?'<button class="fE2D5">Capture</button>':stage==='compose'?'<button class="YatIx">Send To</button>':'<ul role="list"><li class="Ewflr"><span class="RBx9s nonIntl">Approved fixture</span><div class="L7aBq">Select</div></li></ul><button type="submit" class="TYX6O">Send</button>';const button=d.querySelector('button');let handled=false;button.onclick=()=>{if(handled)return;handled=true;if(stage==='camera')show('capture');else if(stage==='capture')show('compose');else if(stage==='compose')show('recipients');else if(acknowledged)d.body.innerHTML='<main>Sent</main>';};}show('camera');const a=createSender({document:d,clock:c,recipients:['Approved fixture'],actionDelay:20,loopDelay:10,targetSnapCount:1,onError:e=>errors.push(e),onState:e=>states.push(e.state)});try{a.start();for(let i=0;i<300;i++)await c.advance(50);await a.stop();assert(states.includes('awaitSendAck'),JSON.stringify({states,errors}));assert.equal(a.getState().snapsSent,acknowledged?1:0);assert.deepEqual(errors,[]);assert.equal(c.pending,0);}finally{await a.dispose();w.close();}});
