import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {JSDOM}=require(process.env.GHOST_TEST_JSDOM||'jsdom');
export function seeded(seed){let state=seed>>>0;return ()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/4294967296);}
export function clock(){let now=1000,id=0;const tasks=new Map();return {now:()=>now,setTimeout(fn,ms){tasks.set(++id,{fn,at:now+Math.max(0,ms)});return id;},clearTimeout:id=>tasks.delete(id),get pending(){return tasks.size;},async advance(ms){const end=now+ms;for(let i=0;i<10000;i++){for(let j=0;j<24;j++)await Promise.resolve();const next=[...tasks].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next){now=end;return;}now=next[1].at;tasks.delete(next[0]);next[1].fn();}throw Error('Clock runaway');}};}
export function fixture(){const dom=new JSDOM('<!doctype html><body></body>',{url:'https://web.snapchat.com',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.getBoundingClientRect=function(){return this.isConnected&&!this.hidden?{width:100,height:30,left:0,top:0,right:100,bottom:30}:{width:0,height:0,left:0,top:0,right:0,bottom:0};};for(const prop of ['offsetWidth','offsetHeight'])Object.defineProperty(w.HTMLElement.prototype,prop,{get(){return this.isConnected&&!this.hidden?100:0;}});w.HTMLElement.prototype.scrollIntoView=()=>{};w.document.elementFromPoint=()=>w.document.querySelector('.vwM69.OXbMa')||w.document.body;return dom;}
export async function pump(c,ms=10000){for(let i=0;i<ms;i+=25)await c.advance(25);}
export function senderPage(d,c,{shortcut=false,delay=0,ack=true,missingRecipient=false,missingSelect=false,replace=false}={}){const stats={clicks:0,selectClicks:0,sendClicks:0};let queued=false;function later(fn){if(!queued){queued=true;c.setTimeout(()=>{queued=false;fn();},delay);}}
 function show(stage){d.body.innerHTML=stage==='camera'?'<button class="qJKfS">Camera</button>':stage==='capture'?'<button class="fE2D5">Capture</button>':stage==='compose'?'<button class="YatIx">Send To</button>':stage==='shortcut'?'<div class="THeKv"><button class="c47Sk">Fixture group</button></div>':stage==='select'?'<button class="Y7u8A">Select</button>':stage==='recipients'?'<ul role="list"><li class="Ewflr"><span class="RBx9s nonIntl">Fixture person</span><div class="L7aBq">Choose</div></li></ul><button type="submit" class="TYX6O">Send</button>':stage==='send'?'<button type="submit" class="TYX6O">Send</button>':'<main>Sent</main>';
 if(missingRecipient&&stage==='recipients')d.querySelector('li').remove();
 if(missingSelect&&stage==='select')d.body.innerHTML='<main>Nothing selectable</main>';
 const button=d.querySelector('button');if(button){button.onclick=()=>{stats.clicks++;if(stage==='camera')later(()=>show('capture'));else if(stage==='capture')later(()=>show('compose'));else if(stage==='compose')later(()=>show(shortcut?'shortcut':'recipients'));else if(stage==='shortcut')later(()=>show('select'));else if(stage==='select'){stats.selectClicks++;later(()=>show('send'));}else {stats.sendClicks++;if(ack)later(()=>show('done'));}};if(replace){const newer=button.cloneNode(true);newer.onclick=button.onclick;button.replaceWith(newer);}}
 }show('camera');return {stats,show};}
export function openerPage(d,c,mode,{delay=70,neverClose=false,replace=false}={}){const stats={clicks:0,closes:0};function list(){d.body.innerHTML=mode==='single'?'<div class="vwM69 OXbMa">View</div>':'<div class="deg2K"><div class="O4POs"><span class="FiLwP">Fixture person</span><span class="giV53"><span class="nonIntl">View</span></span><button class="HEkDJ">View</button></div></div>';let target=d.querySelector(mode==='single'?'.vwM69':'.HEkDJ');target.onclick=()=>{stats.clicks++;c.setTimeout(()=>{d.body.innerHTML='<section><button>Send To</button><button>Download</button><button aria-label="Back">Back</button></section>';d.querySelector('[aria-label]').onclick=()=>{stats.closes++;if(!neverClose)c.setTimeout(list,delay);};},delay);};if(replace){const copy=target.cloneNode(true);copy.onclick=target.onclick;target.replaceWith(copy);}}list();return stats;}
